"use client";

import React, { useEffect, useState } from "react";
import UserNavbar from "@/components/UserNavbar";
import { useSearchParams } from "next/navigation";
import ChatButton from "@/components/chatbutton";

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFDownloadLink,
} from "@react-pdf/renderer";

// PDF Styles
const styles = StyleSheet.create({
  page: {
    backgroundColor: '#f8fafc', // light neutral
    padding: 32,
    fontSize: 13,
    color: '#1e293b',
    fontFamily: 'Helvetica',
  },
  section: {
    marginBottom: 16,
    padding: 0,
  },
  header: {
    fontSize: 22,
    marginBottom: 10,
    fontWeight: 'bold',
    color: '#2563eb', // main blue
    textAlign: 'center',
    letterSpacing: 1,
  },
  subheader: {
    fontSize: 16,
    marginBottom: 8,
    color: '#60a5fa', // accent blue
    textAlign: 'center',
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  label: {
    fontWeight: 'bold',
    color: '#2563eb',
  },
  value: {
    marginLeft: 4,
    color: '#1e293b',
  },
  testBlock: {
    marginBottom: 16,
    padding: 16,
    borderWidth: 2,
    borderColor: '#2563eb',
    borderRadius: 12,
    backgroundColor: '#e0e7ff',
    boxShadow: '0 2px 8px #2563eb33',
  },
  row: {
    flexDirection: 'row',
    marginBottom: 4,
    alignItems: 'baseline',
  },
  footer: {
    marginTop: 24,
    textAlign: 'center',
    color: '#2563eb',
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
});

// PDF Document component
const TestReportPDF = ({ test, patientName, date, labname }) => (
  <Document>
    <Page style={styles.page}>
      <Text style={styles.header}>{labname || 'Lab Name'}</Text>
      <Text style={styles.subheader}>Test Report: {test.name}</Text>
      <View style={styles.section}>
        <View style={styles.row}>
          <Text style={styles.label}>Patient:</Text>
          <Text style={styles.value}>{patientName}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Date:</Text>
          <Text style={styles.value}>{date}</Text>
        </View>
      </View>
      <View style={styles.testBlock}>
        <View style={styles.row}>
          <Text style={styles.label}>Result:</Text>
          <Text style={styles.value}>{test.result || 'N/A'}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Normal Range:</Text>
          <Text style={styles.value}>{test.normalRange || 'N/A'}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Units:</Text>
          <Text style={styles.value}>{test.units || 'N/A'}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Remarks:</Text>
          <Text style={styles.value}>{test.remarks || 'None'}</Text>
        </View>
      </View>
      <Text style={styles.footer}>Generated by Rakshaa Healthcare Platform</Text>
    </Page>
  </Document>
);

const PathlabReportDetailsPage = () => {
  const searchParams = useSearchParams();

  const bookingId = searchParams.get("id");
  const patientName = searchParams.get("patientName") || "Unknown Patient";
  const fee = searchParams.get("fee") || "N/A";
  const date = searchParams.get("date")
    ? new Date(searchParams.get("date")).toLocaleDateString()
    : "N/A";
  const testsList = searchParams.get("tests")
    ? searchParams.get("tests").split(",")
    : [];
  const labname = searchParams.get("labname");
  // console.log("labname" , labname)
  const [testDetails, setTestDetails] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  // Modal state
  const [showModal, setShowModal] = useState(false);
  const [selectedTest, setSelectedTest] = useState(null);

  useEffect(() => {
    if (!bookingId) {
      setError("Booking ID is required to fetch report details.");
      setLoading(false);
      return;
    }

    const fetchReportDetails = async () => {
      setLoading(true);
      setError("");
      try {
        const res = await fetch("/api/pathlab/completed-reports", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ bookingId }),
        });
        const data = await res.json();

        if (data.success) {
          setTestDetails(data.tests || []);
        } else {
          setError(data.message || "Failed to fetch test details.");
        }
      } catch (err) {
        setError("Server error while fetching test details.");
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchReportDetails();
  }, [bookingId]);

  const openModal = (test) => {
    setSelectedTest(test);
    setShowModal(true);
  };

  const closeModal = () => {
    setSelectedTest(null);
    setShowModal(false);
  };

  // Render each test card with View & Download buttons
  const renderTestCard = (test, idx) => (
    <div
      key={idx}
      className="bg-[#2563eb]/10 dark:bg-[#60a5fa]/10 rounded-2xl p-6 shadow-lg space-y-2 border border-[#2563eb]/10 dark:border-[#60a5fa]/10"
    >
      <h3 className="text-xl font-bold text-[#2563eb] dark:text-[#60a5fa] flex items-center gap-2">
        🧪 {test.name}
      </h3>
      <div className="space-y-1 text-[#2563eb] dark:text-[#60a5fa]">
        <p>
          <span className="font-semibold">Result:</span> {test.result || "N/A"}
        </p>
        <p>
          <span className="font-semibold">Normal Range:</span> {test.normalRange || "N/A"}
        </p>
        <p>
          <span className="font-semibold">Units:</span> {test.units || "N/A"}
        </p>
        <p>
          <span className="font-semibold">Remarks:</span> {test.remarks || "None"}
        </p>
      </div>
      <div className="flex gap-4 mt-4">
        <PDFDownloadLink
          document={
            <TestReportPDF
              test={test}
              patientName={patientName}
              date={date}
              labname={labname}
            />
          }
          fileName={`${test.name.replace(/\s+/g, "_")}_Report.pdf`}
          className="bg-green-600 text-white px-4 py-2 rounded-xl font-bold hover:bg-green-700 transition-colors shadow-md flex items-center justify-center"
        >
          {({ loading }) =>
            loading ? "Preparing PDF..." : "Download"
          }
        </PDFDownloadLink>
      </div>
    </div>
  );

  return (
    <>
      <UserNavbar />
      <div className="min-h-screen bg-white dark:bg-[#181c2a] pt-32 pb-10 px-4 sm:px-8">
        <div className="max-w-4xl mx-auto bg-white/95 dark:bg-[#181c2a]/95 border-2 border-[#2563eb]/20 dark:border-[#60a5fa]/20 rounded-3xl shadow-2xl p-8 md:p-12 space-y-10">
          <h1 className="text-4xl font-black text-center text-[#2563eb] dark:text-[#60a5fa] drop-shadow-md tracking-tight">
            Pathlab Report Details
          </h1>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-8 text-[#2563eb] dark:text-[#60a5fa] text-lg font-medium">
            <p>
              <span className="font-semibold">👤 Patient:</span> {patientName}
            </p>
            <p>
              <span className="font-semibold">📅 Date:</span> {date}
            </p>
            <p>
              <span className="font-semibold">🧪 Tests:</span> {testsList.length > 0 ? testsList.join(", ") : "N/A"}
            </p>
            <p>
              <span className="font-semibold">💰 Fee:</span> ₹{fee}
            </p>
          </div>

          {loading ? (
            <p className="text-center text-[#2563eb] dark:text-[#60a5fa] animate-pulse">
              Loading test details...
            </p>
          ) : error ? (
            <p className="text-center text-red-600 dark:text-red-400">{error}</p>
          ) : testDetails.length > 0 ? (
            <div className="space-y-8">
              {testDetails.map((test, idx) => renderTestCard(test, idx))}
            </div>
          ) : (
            <p className="text-center text-[#2563eb]/70 dark:text-[#60a5fa]/70">
              No test details found.
            </p>
          )}
        </div>
      </div>

      {/* Modal */}
      {showModal && selectedTest && (
        <div
          className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
          onClick={closeModal}
        >
          <div
            className="bg-white/95 dark:bg-[#181c2a]/95 rounded-3xl p-8 max-w-lg w-full shadow-2xl border-2 border-[#2563eb]/20 dark:border-[#60a5fa]/20"
            onClick={(e) => e.stopPropagation()}
          >
            <h1 className="text-2xl font-black mb-2 text-[#2563eb] dark:text-[#60a5fa] text-center">
              {labname}
            </h1>
            <h2 className="text-xl font-bold mb-6 text-[#2563eb] dark:text-[#60a5fa] text-center">
              Detailed View: {selectedTest.name}
            </h2>

            <div className="space-y-2 text-[#2563eb] dark:text-[#60a5fa]">
              <p>
                <span className="font-semibold">Result:</span> {selectedTest.result || "N/A"}
              </p>
              <p>
                <span className="font-semibold">Normal Range:</span> {selectedTest.normalRange || "N/A"}
              </p>
              <p>
                <span className="font-semibold">Units:</span> {selectedTest.units || "N/A"}
              </p>
              <p>
                <span className="font-semibold">Remarks:</span> {selectedTest.remarks || "None"}
              </p>
            </div>

            <button
              onClick={closeModal}
              className="mt-8 w-full bg-[#2563eb] dark:bg-[#60a5fa] text-white px-4 py-3 rounded-xl font-bold hover:bg-[#1d4ed8] dark:hover:bg-[#3b82f6] transition-colors shadow-md"
            >
              Close
            </button>
          </div>
        </div>
      )}
      <ChatButton />
    </>
  );
};

export default PathlabReportDetailsPage;
