import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import UserProvider from "@/context/userContext";
import { AmbulanceProvider } from "@/context/AmbulanceContext";
import ChatButton from "@/components/chatbutton";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Raksha",
  description: "Generated by create next app",
};
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import DoctorProvider from "@/context/doctorContext";
import PathlabProvider from "@/context/pathlabContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PathlabProvider>
          <UserProvider>
            <DoctorProvider>
              <AmbulanceProvider>
                {children}
                <ToastContainer position="top-right" autoClose={3000} />
                <ChatButton />
              </AmbulanceProvider>
            </DoctorProvider>
          </UserProvider>
        </PathlabProvider>
      </body>
    </html>
  );
}
